spring:
  sql:
    init.mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/filmotokio
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: lang\res

jwt:
  secret: tokioschool
  expiration: 43200
